config/routes.rb
Rails.application.routes.draw do
resources :my_page
root :to => "my_page#index"

get "index" => "my_page#index"
get  "about" => "my_page#about"
get  "portfolio" => "my_page#portfolio"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/my_page_controller.rb
class MyPageController < ApplicationController
  def index
  end

  def main
  end

  def about
  end

  def portfolio
  end

  def show
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/my_page_helper.rb
module MyPageHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer" >
  <div class="container">
    <p id="copyright">&copy;RubyLupus</p>
  </div>

</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" id="header-nav">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to image_tag("wolf.png"), index_path, class: "navbar-brand logo" %>
      <%= link_to "RubyLupus", index_path, class: "brand" %>
    </div>

    <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right" id="nav-menu">
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Portfolio", portfolio_path %></li>



          </ul>
        </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyLupus</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <!--  <%= favicon_link_tag("favicon_woolf.xcf") %> -->

  <%= analytics_init if GoogleAnalytics.valid_tracker? %>


  </head>

  <body id="main">
    <%= render "layouts/header" %>
    <div class="container">
      <%= yield %>
    </div>
    <br />
    <%= render "layouts/footer"%>


  </body>
</html>

app/views/my_page/about.html.erb
<div class="content">
  <%= image_tag("me.jpg", class: "photo pull-right img-responsive") %>
    <h2 class="text-center">Let me represent some of my passions</h2>

  <div class="text-left">

    <strong>Sport</strong> <br />
    <p>
      I defended the honor of the school playing football, basketball, volleyball and received many awards and repeatedly led the team to victory.<br />At the university, I played basketball a little, after which I go on futsal and play on amateur level several year, I always was the leader of the team.<br /> In recent years, I am inlove by the bodybuilding, so I go to the gym and working with heavy weights.
    </p>
    <strong>Reading/Learning</strong><br />
    <p>
    Another of my passions is reading. Not so long ago I had this passion, but when it's not too late, I have a few topics in mind: computer science, programming languages, personal growth, brain work (consciousness, subconsciousness,why people do so and not otherwise).
    </p>
    <strong>Coding</strong><br />
    <p>
      And, finally, we got to my main passion - programming.
      Since my youth I dreamed of creating something. But something always got in the way. But now nothing can stop me. I will realize all my dreams. And I will achieve this at any cost.
    </p>
  </div>

  <div class="col-lg-6">
    <div>
      <strong>Personality</strong>
    </div>
    <ul class="personal_info">
      <li>responsible</li>
      <li>disciplined</li>
      <li>punctual</li>
      <li>executive</li>
      <li>customer focus</li>
      <li>initiative</li>
    </ul>
  </div>

  <div class="col-lg-6">
    <div>
      <strong>Links</strong>
    </div>
    <ul class="personal_info">
      <li><%= link_to "GitHub", "https://github.com/Scare01"%></li>
    </ul>

  </div>




</div>

app/views/my_page/index.html.erb
<div class="container text-center">
  <div class="jumbotron" id="welcome">
    <h2>Hello there!</h2>
    <p>
      Accidentally or not, but your wandered to my lair. <br />
      In my lair you can find a pair of nooks. In one you can find more information about me, in second, what I create.
    </p>
  </div>
</div>

app/views/my_page/portfolio.html.erb
<div class="content">

</div>